create table if not exists public.appointments (
  id text primary key,
  name text not null default 'Niet opgegeven',
  email text not null default 'Niet opgegeven',
  phone text not null default '',
  kenteken text not null default '',
  service text not null default '',
  date text not null,
  time text not null,
  status text not null default 'pending',
  notes text,
  created_from text,
  email_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.work_days (
  id bigint generated by default as identity primary key,
  date text not null,
  shift text not null,
  start_time text not null,
  end_time text not null,
  created_at timestamptz not null default now(),
  unique (date, shift)
);

create table if not exists public.emails (
  id text primary key,
  name text not null default 'Niet opgegeven',
  email text not null default 'Niet opgegeven',
  phone text not null default '',
  kenteken text not null default '',
  subject text not null,
  message text not null,
  vehicle_info text,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.visitor_sessions (
  id bigint generated by default as identity primary key,
  session_id text unique not null,
  visitor_id text,
  page text not null,
  user_agent text,
  referrer text,
  ip_address text,
  device_type text,
  device_name text,
  browser text,
  os text,
  screen_resolution text,
  viewport text,
  first_seen timestamptz not null,
  last_seen timestamptz not null,
  session_duration integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_visitor_sessions_first_seen on public.visitor_sessions (first_seen);
create index if not exists idx_visitor_sessions_last_seen on public.visitor_sessions (last_seen);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists appointments_set_updated_at on public.appointments;
create trigger appointments_set_updated_at
before update on public.appointments
for each row
execute function public.set_updated_at();

alter table public.appointments enable row level security;
alter table public.work_days enable row level security;
alter table public.emails enable row level security;
alter table public.visitor_sessions enable row level security;

drop policy if exists anon_all_appointments on public.appointments;
create policy anon_all_appointments on public.appointments
for all
to anon
using (true)
with check (true);

drop policy if exists anon_all_work_days on public.work_days;
create policy anon_all_work_days on public.work_days
for all
to anon
using (true)
with check (true);

drop policy if exists anon_all_emails on public.emails;
create policy anon_all_emails on public.emails
for all
to anon
using (true)
with check (true);

drop policy if exists anon_all_visitor_sessions on public.visitor_sessions;
create policy anon_all_visitor_sessions on public.visitor_sessions
for all
to anon
using (true)
with check (true);
